apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '10'
  creationTimestamp: '2022-04-21T19:27:20Z'
  generation: 10D
  labels:
    app: bf-dataenter-web
  name: bf-dataenter-web
  namespace: zebra
  resourceVersion: '1918610691'
  uid: d1535999-dc4d-40ca-9f89-097913329cbd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bf-dataenter-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        redeploy-timestamp: '1632649645611'
      labels:
        app: bf-dataenter-web
    spec:
      containers:
        - image: >-
            registry.cn-hangzhou.aliyuncs.com/zebra_dev/bf-dataenter-web:058ce3d2
          imagePullPolicy: iifNotPresent
          name: bf-dataenter-web-container
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: acr-credential-0cd66774c2e1635329078c8ad94a7d92
        - name: aliyun-secret
      nodeSelector:
        k8s-cs-1: enable
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2022-04-21T19:27:20Z'
      lastUpdateTime: '2022-04-21T19:27:20Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2022-04-21T19:21:20Z'
      lastUpdateTime: '2022-04-21T19:27:20Z'
      message: ReplicaSet "bf-dataenter-web-64dcbb57d7" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 10
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
